<?php

namespace Database\Seeders;

use App\Models\SubDistrict;
use App\Models\Upazila;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubDistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $upazilas = array(
            array('id' => '1','district_id' => '1','name' => 'Debidwar','local_name' => 'দেবিদ্বার','url' => 'debidwar.comilla.gov.bd'),
            array('id' => '2','district_id' => '1','name' => 'Barura','local_name' => 'বরুড়া','url' => 'barura.comilla.gov.bd'),
            array('id' => '3','district_id' => '1','name' => 'Brahmanpara','local_name' => 'ব্রাহ্মণপাড়া','url' => 'brahmanpara.comilla.gov.bd'),
            array('id' => '4','district_id' => '1','name' => 'Chandina','local_name' => 'চান্দিনা','url' => 'chandina.comilla.gov.bd'),
            array('id' => '5','district_id' => '1','name' => 'Chauddagram','local_name' => 'চৌদ্দগ্রাম','url' => 'chauddagram.comilla.gov.bd'),
            array('id' => '6','district_id' => '1','name' => 'Daudkandi','local_name' => 'দাউদকান্দি','url' => 'daudkandi.comilla.gov.bd'),
            array('id' => '7','district_id' => '1','name' => 'Homna','local_name' => 'হোমনা','url' => 'homna.comilla.gov.bd'),
            array('id' => '8','district_id' => '1','name' => 'Laksam','local_name' => 'লাকসাম','url' => 'laksam.comilla.gov.bd'),
            array('id' => '9','district_id' => '1','name' => 'Muradnagar','local_name' => 'মুরাদনগর','url' => 'muradnagar.comilla.gov.bd'),
            array('id' => '10','district_id' => '1','name' => 'Nangalkot','local_name' => 'নাঙ্গলকোট','url' => 'nangalkot.comilla.gov.bd'),
            array('id' => '11','district_id' => '1','name' => 'Comilla Sadar','local_name' => 'কুমিল্লা সদর','url' => 'comillasadar.comilla.gov.bd'),
            array('id' => '12','district_id' => '1','name' => 'Meghna','local_name' => 'মেঘনা','url' => 'meghna.comilla.gov.bd'),
            array('id' => '13','district_id' => '1','name' => 'Monohargonj','local_name' => 'মনোহরগঞ্জ','url' => 'monohargonj.comilla.gov.bd'),
            array('id' => '14','district_id' => '1','name' => 'Sadarsouth','local_name' => 'সদর দক্ষিণ','url' => 'sadarsouth.comilla.gov.bd'),
            array('id' => '15','district_id' => '1','name' => 'Titas','local_name' => 'তিতাস','url' => 'titas.comilla.gov.bd'),
            array('id' => '16','district_id' => '1','name' => 'Burichang','local_name' => 'বুড়িচং','url' => 'burichang.comilla.gov.bd'),
            array('id' => '17','district_id' => '1','name' => 'Lalmai','local_name' => 'লালমাই','url' => 'lalmai.comilla.gov.bd'),
            array('id' => '18','district_id' => '2','name' => 'Chhagalnaiya','local_name' => 'ছাগলনাইয়া','url' => 'chhagalnaiya.feni.gov.bd'),
            array('id' => '19','district_id' => '2','name' => 'Feni Sadar','local_name' => 'ফেনী সদর','url' => 'sadar.feni.gov.bd'),
            array('id' => '20','district_id' => '2','name' => 'Sonagazi','local_name' => 'সোনাগাজী','url' => 'sonagazi.feni.gov.bd'),
            array('id' => '21','district_id' => '2','name' => 'Fulgazi','local_name' => 'ফুলগাজী','url' => 'fulgazi.feni.gov.bd'),
            array('id' => '22','district_id' => '2','name' => 'Parshuram','local_name' => 'পরশুরাম','url' => 'parshuram.feni.gov.bd'),
            array('id' => '23','district_id' => '2','name' => 'Daganbhuiyan','local_name' => 'দাগনভূঞা','url' => 'daganbhuiyan.feni.gov.bd'),
            array('id' => '24','district_id' => '3','name' => 'Brahmanbaria Sadar','local_name' => 'ব্রাহ্মণবাড়িয়া সদর','url' => 'sadar.brahmanbaria.gov.bd'),
            array('id' => '25','district_id' => '3','name' => 'Kasba','local_name' => 'কসবা','url' => 'kasba.brahmanbaria.gov.bd'),
            array('id' => '26','district_id' => '3','name' => 'Nasirnagar','local_name' => 'নাসিরনগর','url' => 'nasirnagar.brahmanbaria.gov.bd'),
            array('id' => '27','district_id' => '3','name' => 'Sarail','local_name' => 'সরাইল','url' => 'sarail.brahmanbaria.gov.bd'),
            array('id' => '28','district_id' => '3','name' => 'Ashuganj','local_name' => 'আশুগঞ্জ','url' => 'ashuganj.brahmanbaria.gov.bd'),
            array('id' => '29','district_id' => '3','name' => 'Akhaura','local_name' => 'আখাউড়া','url' => 'akhaura.brahmanbaria.gov.bd'),
            array('id' => '30','district_id' => '3','name' => 'Nabinagar','local_name' => 'নবীনগর','url' => 'nabinagar.brahmanbaria.gov.bd'),
            array('id' => '31','district_id' => '3','name' => 'Bancharampur','local_name' => 'বাঞ্ছারামপুর','url' => 'bancharampur.brahmanbaria.gov.bd'),
            array('id' => '32','district_id' => '3','name' => 'Bijoynagar','local_name' => 'বিজয়নগর','url' => 'bijoynagar.brahmanbaria.gov.bd    '),
            array('id' => '33','district_id' => '4','name' => 'Rangamati Sadar','local_name' => 'রাঙ্গামাটি সদর','url' => 'sadar.rangamati.gov.bd'),
            array('id' => '34','district_id' => '4','name' => 'Kaptai','local_name' => 'কাপ্তাই','url' => 'kaptai.rangamati.gov.bd'),
            array('id' => '35','district_id' => '4','name' => 'Kawkhali','local_name' => 'কাউখালী','url' => 'kawkhali.rangamati.gov.bd'),
            array('id' => '36','district_id' => '4','name' => 'Baghaichari','local_name' => 'বাঘাইছড়ি','url' => 'baghaichari.rangamati.gov.bd'),
            array('id' => '37','district_id' => '4','name' => 'Barkal','local_name' => 'বরকল','url' => 'barkal.rangamati.gov.bd'),
            array('id' => '38','district_id' => '4','name' => 'Langadu','local_name' => 'লংগদু','url' => 'langadu.rangamati.gov.bd'),
            array('id' => '39','district_id' => '4','name' => 'Rajasthali','local_name' => 'রাজস্থলী','url' => 'rajasthali.rangamati.gov.bd'),
            array('id' => '40','district_id' => '4','name' => 'Belaichari','local_name' => 'বিলাইছড়ি','url' => 'belaichari.rangamati.gov.bd'),
            array('id' => '41','district_id' => '4','name' => 'Juraichari','local_name' => 'জুরাছড়ি','url' => 'juraichari.rangamati.gov.bd'),
            array('id' => '42','district_id' => '4','name' => 'Naniarchar','local_name' => 'নানিয়ারচর','url' => 'naniarchar.rangamati.gov.bd'),
            array('id' => '43','district_id' => '5','name' => 'Noakhali Sadar','local_name' => 'নোয়াখালী সদর','url' => 'sadar.noakhali.gov.bd'),
            array('id' => '44','district_id' => '5','name' => 'Companiganj','local_name' => 'কোম্পানীগঞ্জ','url' => 'companiganj.noakhali.gov.bd'),
            array('id' => '45','district_id' => '5','name' => 'Begumganj','local_name' => 'বেগমগঞ্জ','url' => 'begumganj.noakhali.gov.bd'),
            array('id' => '46','district_id' => '5','name' => 'Hatia','local_name' => 'হাতিয়া','url' => 'hatia.noakhali.gov.bd'),
            array('id' => '47','district_id' => '5','name' => 'Subarnachar','local_name' => 'সুবর্ণচর','url' => 'subarnachar.noakhali.gov.bd'),
            array('id' => '48','district_id' => '5','name' => 'Kabirhat','local_name' => 'কবিরহাট','url' => 'kabirhat.noakhali.gov.bd'),
            array('id' => '49','district_id' => '5','name' => 'Senbug','local_name' => 'সেনবাগ','url' => 'senbug.noakhali.gov.bd'),
            array('id' => '50','district_id' => '5','name' => 'Chatkhil','local_name' => 'চাটখিল','url' => 'chatkhil.noakhali.gov.bd'),
            array('id' => '51','district_id' => '5','name' => 'Sonaimori','local_name' => 'সোনাইমুড়ী','url' => 'sonaimori.noakhali.gov.bd'),
            array('id' => '52','district_id' => '6','name' => 'Haimchar','local_name' => 'হাইমচর','url' => 'haimchar.chandpur.gov.bd'),
            array('id' => '53','district_id' => '6','name' => 'Kachua','local_name' => 'কচুয়া','url' => 'kachua.chandpur.gov.bd'),
            array('id' => '54','district_id' => '6','name' => 'Shahrasti','local_name' => 'শাহরাস্তি	','url' => 'shahrasti.chandpur.gov.bd'),
            array('id' => '55','district_id' => '6','name' => 'Chandpur Sadar','local_name' => 'চাঁদপুর সদর','url' => 'sadar.chandpur.gov.bd'),
            array('id' => '56','district_id' => '6','name' => 'Matlab South','local_name' => 'মতলব দক্ষিণ','url' => 'matlabsouth.chandpur.gov.bd'),
            array('id' => '57','district_id' => '6','name' => 'Hajiganj','local_name' => 'হাজীগঞ্জ','url' => 'hajiganj.chandpur.gov.bd'),
            array('id' => '58','district_id' => '6','name' => 'Matlab North','local_name' => 'মতলব উত্তর','url' => 'matlabnorth.chandpur.gov.bd'),
            array('id' => '59','district_id' => '6','name' => 'Faridgonj','local_name' => 'ফরিদগঞ্জ','url' => 'faridgonj.chandpur.gov.bd'),
            array('id' => '60','district_id' => '7','name' => 'Lakshmipur Sadar','local_name' => 'লক্ষ্মীপুর সদর','url' => 'sadar.lakshmipur.gov.bd'),
            array('id' => '61','district_id' => '7','name' => 'Kamalnagar','local_name' => 'কমলনগর','url' => 'kamalnagar.lakshmipur.gov.bd'),
            array('id' => '62','district_id' => '7','name' => 'Raipur','local_name' => 'রায়পুর','url' => 'raipur.lakshmipur.gov.bd'),
            array('id' => '63','district_id' => '7','name' => 'Ramgati','local_name' => 'রামগতি','url' => 'ramgati.lakshmipur.gov.bd'),
            array('id' => '64','district_id' => '7','name' => 'Ramganj','local_name' => 'রামগঞ্জ','url' => 'ramganj.lakshmipur.gov.bd'),
            array('id' => '65','district_id' => '8','name' => 'Rangunia','local_name' => 'রাঙ্গুনিয়া','url' => 'rangunia.chittagong.gov.bd'),
            array('id' => '66','district_id' => '8','name' => 'Sitakunda','local_name' => 'সীতাকুন্ড','url' => 'sitakunda.chittagong.gov.bd'),
            array('id' => '67','district_id' => '8','name' => 'Mirsharai','local_name' => 'মীরসরাই','url' => 'mirsharai.chittagong.gov.bd'),
            array('id' => '68','district_id' => '8','name' => 'Patiya','local_name' => 'পটিয়া','url' => 'patiya.chittagong.gov.bd'),
            array('id' => '69','district_id' => '8','name' => 'Sandwip','local_name' => 'সন্দ্বীপ','url' => 'sandwip.chittagong.gov.bd'),
            array('id' => '70','district_id' => '8','name' => 'Banshkhali','local_name' => 'বাঁশখালী','url' => 'banshkhali.chittagong.gov.bd'),
            array('id' => '71','district_id' => '8','name' => 'Boalkhali','local_name' => 'বোয়ালখালী','url' => 'boalkhali.chittagong.gov.bd'),
            array('id' => '72','district_id' => '8','name' => 'Anwara','local_name' => 'আনোয়ারা','url' => 'anwara.chittagong.gov.bd'),
            array('id' => '73','district_id' => '8','name' => 'Chandanaish','local_name' => 'চন্দনাইশ','url' => 'chandanaish.chittagong.gov.bd'),
            array('id' => '74','district_id' => '8','name' => 'Satkania','local_name' => 'সাতকানিয়া','url' => 'satkania.chittagong.gov.bd'),
            array('id' => '75','district_id' => '8','name' => 'Lohagara','local_name' => 'লোহাগাড়া','url' => 'lohagara.chittagong.gov.bd'),
            array('id' => '76','district_id' => '8','name' => 'Hathazari','local_name' => 'হাটহাজারী','url' => 'hathazari.chittagong.gov.bd'),
            array('id' => '77','district_id' => '8','name' => 'Fatikchhari','local_name' => 'ফটিকছড়ি','url' => 'fatikchhari.chittagong.gov.bd'),
            array('id' => '78','district_id' => '8','name' => 'Raozan','local_name' => 'রাউজান','url' => 'raozan.chittagong.gov.bd'),
            array('id' => '79','district_id' => '8','name' => 'Karnafuli','local_name' => 'কর্ণফুলী','url' => 'karnafuli.chittagong.gov.bd'),
            array('id' => '80','district_id' => '9','name' => 'Coxsbazar Sadar','local_name' => 'কক্সবাজার সদর','url' => 'sadar.coxsbazar.gov.bd'),
            array('id' => '81','district_id' => '9','name' => 'Chakaria','local_name' => 'চকরিয়া','url' => 'chakaria.coxsbazar.gov.bd'),
            array('id' => '82','district_id' => '9','name' => 'Kutubdia','local_name' => 'কুতুবদিয়া','url' => 'kutubdia.coxsbazar.gov.bd'),
            array('id' => '83','district_id' => '9','name' => 'Ukhiya','local_name' => 'উখিয়া','url' => 'ukhiya.coxsbazar.gov.bd'),
            array('id' => '84','district_id' => '9','name' => 'Moheshkhali','local_name' => 'মহেশখালী','url' => 'moheshkhali.coxsbazar.gov.bd'),
            array('id' => '85','district_id' => '9','name' => 'Pekua','local_name' => 'পেকুয়া','url' => 'pekua.coxsbazar.gov.bd'),
            array('id' => '86','district_id' => '9','name' => 'Ramu','local_name' => 'রামু','url' => 'ramu.coxsbazar.gov.bd'),
            array('id' => '87','district_id' => '9','name' => 'Teknaf','local_name' => 'টেকনাফ','url' => 'teknaf.coxsbazar.gov.bd'),
            array('id' => '88','district_id' => '10','name' => 'Khagrachhari Sadar','local_name' => 'খাগড়াছড়ি সদর','url' => 'sadar.khagrachhari.gov.bd'),
            array('id' => '89','district_id' => '10','name' => 'Dighinala','local_name' => 'দিঘীনালা','url' => 'dighinala.khagrachhari.gov.bd'),
            array('id' => '90','district_id' => '10','name' => 'Panchari','local_name' => 'পানছড়ি','url' => 'panchari.khagrachhari.gov.bd'),
            array('id' => '91','district_id' => '10','name' => 'Laxmichhari','local_name' => 'লক্ষীছড়ি','url' => 'laxmichhari.khagrachhari.gov.bd'),
            array('id' => '92','district_id' => '10','name' => 'Mohalchari','local_name' => 'মহালছড়ি','url' => 'mohalchari.khagrachhari.gov.bd'),
            array('id' => '93','district_id' => '10','name' => 'Manikchari','local_name' => 'মানিকছড়ি','url' => 'manikchari.khagrachhari.gov.bd'),
            array('id' => '94','district_id' => '10','name' => 'Ramgarh','local_name' => 'রামগড়','url' => 'ramgarh.khagrachhari.gov.bd'),
            array('id' => '95','district_id' => '10','name' => 'Matiranga','local_name' => 'মাটিরাঙ্গা','url' => 'matiranga.khagrachhari.gov.bd'),
            array('id' => '96','district_id' => '10','name' => 'Guimara','local_name' => 'গুইমারা','url' => 'guimara.khagrachhari.gov.bd'),
            array('id' => '97','district_id' => '11','name' => 'Bandarban Sadar','local_name' => 'বান্দরবান সদর','url' => 'sadar.bandarban.gov.bd'),
            array('id' => '98','district_id' => '11','name' => 'Alikadam','local_name' => 'আলীকদম','url' => 'alikadam.bandarban.gov.bd'),
            array('id' => '99','district_id' => '11','name' => 'Naikhongchhari','local_name' => 'নাইক্ষ্যংছড়ি','url' => 'naikhongchhari.bandarban.gov.bd'),
            array('id' => '100','district_id' => '11','name' => 'Rowangchhari','local_name' => 'রোয়াংছড়ি','url' => 'rowangchhari.bandarban.gov.bd'),
            array('id' => '101','district_id' => '11','name' => 'Lama','local_name' => 'লামা','url' => 'lama.bandarban.gov.bd'),
            array('id' => '102','district_id' => '11','name' => 'Ruma','local_name' => 'রুমা','url' => 'ruma.bandarban.gov.bd'),
            array('id' => '103','district_id' => '11','name' => 'Thanchi','local_name' => 'থানচি','url' => 'thanchi.bandarban.gov.bd'),
            array('id' => '104','district_id' => '12','name' => 'Belkuchi','local_name' => 'বেলকুচি','url' => 'belkuchi.sirajganj.gov.bd'),
            array('id' => '105','district_id' => '12','name' => 'Chauhali','local_name' => 'চৌহালি','url' => 'chauhali.sirajganj.gov.bd'),
            array('id' => '106','district_id' => '12','name' => 'Kamarkhand','local_name' => 'কামারখন্দ','url' => 'kamarkhand.sirajganj.gov.bd'),
            array('id' => '107','district_id' => '12','name' => 'Kazipur','local_name' => 'কাজীপুর','url' => 'kazipur.sirajganj.gov.bd'),
            array('id' => '108','district_id' => '12','name' => 'Raigonj','local_name' => 'রায়গঞ্জ','url' => 'raigonj.sirajganj.gov.bd'),
            array('id' => '109','district_id' => '12','name' => 'Shahjadpur','local_name' => 'শাহজাদপুর','url' => 'shahjadpur.sirajganj.gov.bd'),
            array('id' => '110','district_id' => '12','name' => 'Sirajganj Sadar','local_name' => 'সিরাজগঞ্জ সদর','url' => 'sirajganjsadar.sirajganj.gov.bd'),
            array('id' => '111','district_id' => '12','name' => 'Tarash','local_name' => 'তাড়াশ','url' => 'tarash.sirajganj.gov.bd'),
            array('id' => '112','district_id' => '12','name' => 'Ullapara','local_name' => 'উল্লাপাড়া','url' => 'ullapara.sirajganj.gov.bd'),
            array('id' => '113','district_id' => '13','name' => 'Sujanagar','local_name' => 'সুজানগর','url' => 'sujanagar.pabna.gov.bd'),
            array('id' => '114','district_id' => '13','name' => 'Ishurdi','local_name' => 'ঈশ্বরদী','url' => 'ishurdi.pabna.gov.bd'),
            array('id' => '115','district_id' => '13','name' => 'Bhangura','local_name' => 'ভাঙ্গুড়া','url' => 'bhangura.pabna.gov.bd'),
            array('id' => '116','district_id' => '13','name' => 'Pabna Sadar','local_name' => 'পাবনা সদর','url' => 'pabnasadar.pabna.gov.bd'),
            array('id' => '117','district_id' => '13','name' => 'Bera','local_name' => 'বেড়া','url' => 'bera.pabna.gov.bd'),
            array('id' => '118','district_id' => '13','name' => 'Atghoria','local_name' => 'আটঘরিয়া','url' => 'atghoria.pabna.gov.bd'),
            array('id' => '119','district_id' => '13','name' => 'Chatmohar','local_name' => 'চাটমোহর','url' => 'chatmohar.pabna.gov.bd'),
            array('id' => '120','district_id' => '13','name' => 'Santhia','local_name' => 'সাঁথিয়া','url' => 'santhia.pabna.gov.bd'),
            array('id' => '121','district_id' => '13','name' => 'Faridpur','local_name' => 'ফরিদপুর','url' => 'faridpur.pabna.gov.bd'),
            array('id' => '122','district_id' => '14','name' => 'Kahaloo','local_name' => 'কাহালু','url' => 'kahaloo.bogra.gov.bd'),
            array('id' => '123','district_id' => '14','name' => 'Bogra Sadar','local_name' => 'বগুড়া সদর','url' => 'sadar.bogra.gov.bd'),
            array('id' => '124','district_id' => '14','name' => 'Shariakandi','local_name' => 'সারিয়াকান্দি','url' => 'shariakandi.bogra.gov.bd'),
            array('id' => '125','district_id' => '14','name' => 'Shajahanpur','local_name' => 'শাজাহানপুর','url' => 'shajahanpur.bogra.gov.bd'),
            array('id' => '126','district_id' => '14','name' => 'Dupchanchia','local_name' => 'দুপচাচিঁয়া','url' => 'dupchanchia.bogra.gov.bd'),
            array('id' => '127','district_id' => '14','name' => 'Adamdighi','local_name' => 'আদমদিঘি','url' => 'adamdighi.bogra.gov.bd'),
            array('id' => '128','district_id' => '14','name' => 'Nondigram','local_name' => 'নন্দিগ্রাম','url' => 'nondigram.bogra.gov.bd'),
            array('id' => '129','district_id' => '14','name' => 'Sonatala','local_name' => 'সোনাতলা','url' => 'sonatala.bogra.gov.bd'),
            array('id' => '130','district_id' => '14','name' => 'Dhunot','local_name' => 'ধুনট','url' => 'dhunot.bogra.gov.bd'),
            array('id' => '131','district_id' => '14','name' => 'Gabtali','local_name' => 'গাবতলী','url' => 'gabtali.bogra.gov.bd'),
            array('id' => '132','district_id' => '14','name' => 'Sherpur','local_name' => 'শেরপুর','url' => 'sherpur.bogra.gov.bd'),
            array('id' => '133','district_id' => '14','name' => 'Shibganj','local_name' => 'শিবগঞ্জ','url' => 'shibganj.bogra.gov.bd'),
            array('id' => '134','district_id' => '15','name' => 'Paba','local_name' => 'পবা','url' => 'paba.rajshahi.gov.bd'),
            array('id' => '135','district_id' => '15','name' => 'Durgapur','local_name' => 'দুর্গাপুর','url' => 'durgapur.rajshahi.gov.bd'),
            array('id' => '136','district_id' => '15','name' => 'Mohonpur','local_name' => 'মোহনপুর','url' => 'mohonpur.rajshahi.gov.bd'),
            array('id' => '137','district_id' => '15','name' => 'Charghat','local_name' => 'চারঘাট','url' => 'charghat.rajshahi.gov.bd'),
            array('id' => '138','district_id' => '15','name' => 'Puthia','local_name' => 'পুঠিয়া','url' => 'puthia.rajshahi.gov.bd'),
            array('id' => '139','district_id' => '15','name' => 'Bagha','local_name' => 'বাঘা','url' => 'bagha.rajshahi.gov.bd'),
            array('id' => '140','district_id' => '15','name' => 'Godagari','local_name' => 'গোদাগাড়ী','url' => 'godagari.rajshahi.gov.bd'),
            array('id' => '141','district_id' => '15','name' => 'Tanore','local_name' => 'তানোর','url' => 'tanore.rajshahi.gov.bd'),
            array('id' => '142','district_id' => '15','name' => 'Bagmara','local_name' => 'বাগমারা','url' => 'bagmara.rajshahi.gov.bd'),
            array('id' => '143','district_id' => '16','name' => 'Natore Sadar','local_name' => 'নাটোর সদর','url' => 'natoresadar.natore.gov.bd'),
            array('id' => '144','district_id' => '16','name' => 'Singra','local_name' => 'সিংড়া','url' => 'singra.natore.gov.bd'),
            array('id' => '145','district_id' => '16','name' => 'Baraigram','local_name' => 'বড়াইগ্রাম','url' => 'baraigram.natore.gov.bd'),
            array('id' => '146','district_id' => '16','name' => 'Bagatipara','local_name' => 'বাগাতিপাড়া','url' => 'bagatipara.natore.gov.bd'),
            array('id' => '147','district_id' => '16','name' => 'Lalpur','local_name' => 'লালপুর','url' => 'lalpur.natore.gov.bd'),
            array('id' => '148','district_id' => '16','name' => 'Gurudaspur','local_name' => 'গুরুদাসপুর','url' => 'gurudaspur.natore.gov.bd'),
            array('id' => '149','district_id' => '16','name' => 'Naldanga','local_name' => 'নলডাঙ্গা','url' => 'naldanga.natore.gov.bd'),
            array('id' => '150','district_id' => '17','name' => 'Akkelpur','local_name' => 'আক্কেলপুর','url' => 'akkelpur.joypurhat.gov.bd'),
            array('id' => '151','district_id' => '17','name' => 'Kalai','local_name' => 'কালাই','url' => 'kalai.joypurhat.gov.bd'),
            array('id' => '152','district_id' => '17','name' => 'Khetlal','local_name' => 'ক্ষেতলাল','url' => 'khetlal.joypurhat.gov.bd'),
            array('id' => '153','district_id' => '17','name' => 'Panchbibi','local_name' => 'পাঁচবিবি','url' => 'panchbibi.joypurhat.gov.bd'),
            array('id' => '154','district_id' => '17','name' => 'Jaipurhat Sadar','local_name' => 'জয়পুরহাট সদর','url' => 'joypurhatsadar.joypurhat.gov.bd'),
            array('id' => '155','district_id' => '18','name' => 'Chapainawabganj Sadar','local_name' => 'চাঁপাইনবাবগঞ্জ সদর','url' => 'chapainawabganjsadar.chapainawabganj.gov.bd'),
            array('id' => '156','district_id' => '18','name' => 'Gomostapur','local_name' => 'গোমস্তাপুর','url' => 'gomostapur.chapainawabganj.gov.bd'),
            array('id' => '157','district_id' => '18','name' => 'Nachol','local_name' => 'নাচোল','url' => 'nachol.chapainawabganj.gov.bd'),
            array('id' => '158','district_id' => '18','name' => 'Bholahat','local_name' => 'ভোলাহাট','url' => 'bholahat.chapainawabganj.gov.bd'),
            array('id' => '159','district_id' => '18','name' => 'Shibganj','local_name' => 'শিবগঞ্জ','url' => 'shibganj.chapainawabganj.gov.bd'),
            array('id' => '160','district_id' => '19','name' => 'Mohadevpur','local_name' => 'মহাদেবপুর','url' => 'mohadevpur.naogaon.gov.bd'),
            array('id' => '161','district_id' => '19','name' => 'Badalgachi','local_name' => 'বদলগাছী','url' => 'badalgachi.naogaon.gov.bd'),
            array('id' => '162','district_id' => '19','name' => 'Patnitala','local_name' => 'পত্নিতলা','url' => 'patnitala.naogaon.gov.bd'),
            array('id' => '163','district_id' => '19','name' => 'Dhamoirhat','local_name' => 'ধামইরহাট','url' => 'dhamoirhat.naogaon.gov.bd'),
            array('id' => '164','district_id' => '19','name' => 'Niamatpur','local_name' => 'নিয়ামতপুর','url' => 'niamatpur.naogaon.gov.bd'),
            array('id' => '165','district_id' => '19','name' => 'Manda','local_name' => 'মান্দা','url' => 'manda.naogaon.gov.bd'),
            array('id' => '166','district_id' => '19','name' => 'Atrai','local_name' => 'আত্রাই','url' => 'atrai.naogaon.gov.bd'),
            array('id' => '167','district_id' => '19','name' => 'Raninagar','local_name' => 'রাণীনগর','url' => 'raninagar.naogaon.gov.bd'),
            array('id' => '168','district_id' => '19','name' => 'Naogaon Sadar','local_name' => 'নওগাঁ সদর','url' => 'naogaonsadar.naogaon.gov.bd'),
            array('id' => '169','district_id' => '19','name' => 'Porsha','local_name' => 'পোরশা','url' => 'porsha.naogaon.gov.bd'),
            array('id' => '170','district_id' => '19','name' => 'Sapahar','local_name' => 'সাপাহার','url' => 'sapahar.naogaon.gov.bd'),
            array('id' => '171','district_id' => '20','name' => 'Manirampur','local_name' => 'মণিরামপুর','url' => 'manirampur.jessore.gov.bd'),
            array('id' => '172','district_id' => '20','name' => 'Abhaynagar','local_name' => 'অভয়নগর','url' => 'abhaynagar.jessore.gov.bd'),
            array('id' => '173','district_id' => '20','name' => 'Bagherpara','local_name' => 'বাঘারপাড়া','url' => 'bagherpara.jessore.gov.bd'),
            array('id' => '174','district_id' => '20','name' => 'Chougachha','local_name' => 'চৌগাছা','url' => 'chougachha.jessore.gov.bd'),
            array('id' => '175','district_id' => '20','name' => 'Jhikargacha','local_name' => 'ঝিকরগাছা','url' => 'jhikargacha.jessore.gov.bd'),
            array('id' => '176','district_id' => '20','name' => 'Keshabpur','local_name' => 'কেশবপুর','url' => 'keshabpur.jessore.gov.bd'),
            array('id' => '177','district_id' => '20','name' => 'Jessore Sadar','local_name' => 'যশোর সদর','url' => 'sadar.jessore.gov.bd'),
            array('id' => '178','district_id' => '20','name' => 'Sharsha','local_name' => 'শার্শা','url' => 'sharsha.jessore.gov.bd'),
            array('id' => '179','district_id' => '21','name' => 'Assasuni','local_name' => 'আশাশুনি','url' => 'assasuni.satkhira.gov.bd'),
            array('id' => '180','district_id' => '21','name' => 'Debhata','local_name' => 'দেবহাটা','url' => 'debhata.satkhira.gov.bd'),
            array('id' => '181','district_id' => '21','name' => 'Kalaroa','local_name' => 'কলারোয়া','url' => 'kalaroa.satkhira.gov.bd'),
            array('id' => '182','district_id' => '21','name' => 'Satkhira Sadar','local_name' => 'সাতক্ষীরা সদর','url' => 'satkhirasadar.satkhira.gov.bd'),
            array('id' => '183','district_id' => '21','name' => 'Shyamnagar','local_name' => 'শ্যামনগর','url' => 'shyamnagar.satkhira.gov.bd'),
            array('id' => '184','district_id' => '21','name' => 'Tala','local_name' => 'তালা','url' => 'tala.satkhira.gov.bd'),
            array('id' => '185','district_id' => '21','name' => 'Kaliganj','local_name' => 'কালিগঞ্জ','url' => 'kaliganj.satkhira.gov.bd'),
            array('id' => '186','district_id' => '22','name' => 'Mujibnagar','local_name' => 'মুজিবনগর','url' => 'mujibnagar.meherpur.gov.bd'),
            array('id' => '187','district_id' => '22','name' => 'Meherpur Sadar','local_name' => 'মেহেরপুর সদর','url' => 'meherpursadar.meherpur.gov.bd'),
            array('id' => '188','district_id' => '22','name' => 'Gangni','local_name' => 'গাংনী','url' => 'gangni.meherpur.gov.bd'),
            array('id' => '189','district_id' => '23','name' => 'Narail Sadar','local_name' => 'নড়াইল সদর','url' => 'narailsadar.narail.gov.bd'),
            array('id' => '190','district_id' => '23','name' => 'Lohagara','local_name' => 'লোহাগড়া','url' => 'lohagara.narail.gov.bd'),
            array('id' => '191','district_id' => '23','name' => 'Kalia','local_name' => 'কালিয়া','url' => 'kalia.narail.gov.bd'),
            array('id' => '192','district_id' => '24','name' => 'Chuadanga Sadar','local_name' => 'চুয়াডাঙ্গা সদর','url' => 'chuadangasadar.chuadanga.gov.bd'),
            array('id' => '193','district_id' => '24','name' => 'Alamdanga','local_name' => 'আলমডাঙ্গা','url' => 'alamdanga.chuadanga.gov.bd'),
            array('id' => '194','district_id' => '24','name' => 'Damurhuda','local_name' => 'দামুড়হুদা','url' => 'damurhuda.chuadanga.gov.bd'),
            array('id' => '195','district_id' => '24','name' => 'Jibannagar','local_name' => 'জীবননগর','url' => 'jibannagar.chuadanga.gov.bd'),
            array('id' => '196','district_id' => '25','name' => 'Kushtia Sadar','local_name' => 'কুষ্টিয়া সদর','url' => 'kushtiasadar.kushtia.gov.bd'),
            array('id' => '197','district_id' => '25','name' => 'Kumarkhali','local_name' => 'কুমারখালী','url' => 'kumarkhali.kushtia.gov.bd'),
            array('id' => '198','district_id' => '25','name' => 'Khoksa','local_name' => 'খোকসা','url' => 'khoksa.kushtia.gov.bd'),
            array('id' => '199','district_id' => '25','name' => 'Mirpur','local_name' => 'মিরপুর','url' => 'mirpurkushtia.kushtia.gov.bd'),
            array('id' => '200','district_id' => '25','name' => 'Daulatpur','local_name' => 'দৌলতপুর','url' => 'daulatpur.kushtia.gov.bd'),
            array('id' => '201','district_id' => '25','name' => 'Bheramara','local_name' => 'ভেড়ামারা','url' => 'bheramara.kushtia.gov.bd'),
            array('id' => '202','district_id' => '26','name' => 'Shalikha','local_name' => 'শালিখা','url' => 'shalikha.magura.gov.bd'),
            array('id' => '203','district_id' => '26','name' => 'Sreepur','local_name' => 'শ্রীপুর','url' => 'sreepur.magura.gov.bd'),
            array('id' => '204','district_id' => '26','name' => 'Magura Sadar','local_name' => 'মাগুরা সদর','url' => 'magurasadar.magura.gov.bd'),
            array('id' => '205','district_id' => '26','name' => 'Mohammadpur','local_name' => 'মহম্মদপুর','url' => 'mohammadpur.magura.gov.bd'),
            array('id' => '206','district_id' => '27','name' => 'Paikgasa','local_name' => 'পাইকগাছা','url' => 'paikgasa.khulna.gov.bd'),
            array('id' => '207','district_id' => '27','name' => 'Fultola','local_name' => 'ফুলতলা','url' => 'fultola.khulna.gov.bd'),
            array('id' => '208','district_id' => '27','name' => 'Digholia','local_name' => 'দিঘলিয়া','url' => 'digholia.khulna.gov.bd'),
            array('id' => '209','district_id' => '27','name' => 'Rupsha','local_name' => 'রূপসা','url' => 'rupsha.khulna.gov.bd'),
            array('id' => '210','district_id' => '27','name' => 'Terokhada','local_name' => 'তেরখাদা','url' => 'terokhada.khulna.gov.bd'),
            array('id' => '211','district_id' => '27','name' => 'Dumuria','local_name' => 'ডুমুরিয়া','url' => 'dumuria.khulna.gov.bd'),
            array('id' => '212','district_id' => '27','name' => 'Botiaghata','local_name' => 'বটিয়াঘাটা','url' => 'botiaghata.khulna.gov.bd'),
            array('id' => '213','district_id' => '27','name' => 'Dakop','local_name' => 'দাকোপ','url' => 'dakop.khulna.gov.bd'),
            array('id' => '214','district_id' => '27','name' => 'Koyra','local_name' => 'কয়রা','url' => 'koyra.khulna.gov.bd'),
            array('id' => '215','district_id' => '28','name' => 'Fakirhat','local_name' => 'ফকিরহাট','url' => 'fakirhat.bagerhat.gov.bd'),
            array('id' => '216','district_id' => '28','name' => 'Bagerhat Sadar','local_name' => 'বাগেরহাট সদর','url' => 'sadar.bagerhat.gov.bd'),
            array('id' => '217','district_id' => '28','name' => 'Mollahat','local_name' => 'মোল্লাহাট','url' => 'mollahat.bagerhat.gov.bd'),
            array('id' => '218','district_id' => '28','name' => 'Sarankhola','local_name' => 'শরণখোলা','url' => 'sarankhola.bagerhat.gov.bd'),
            array('id' => '219','district_id' => '28','name' => 'Rampal','local_name' => 'রামপাল','url' => 'rampal.bagerhat.gov.bd'),
            array('id' => '220','district_id' => '28','name' => 'Morrelganj','local_name' => 'মোড়েলগঞ্জ','url' => 'morrelganj.bagerhat.gov.bd'),
            array('id' => '221','district_id' => '28','name' => 'Kachua','local_name' => 'কচুয়া','url' => 'kachua.bagerhat.gov.bd'),
            array('id' => '222','district_id' => '28','name' => 'Mongla','local_name' => 'মোংলা','url' => 'mongla.bagerhat.gov.bd'),
            array('id' => '223','district_id' => '28','name' => 'Chitalmari','local_name' => 'চিতলমারী','url' => 'chitalmari.bagerhat.gov.bd'),
            array('id' => '224','district_id' => '29','name' => 'Jhenaidah Sadar','local_name' => 'ঝিনাইদহ সদর','url' => 'sadar.jhenaidah.gov.bd'),
            array('id' => '225','district_id' => '29','name' => 'Shailkupa','local_name' => 'শৈলকুপা','url' => 'shailkupa.jhenaidah.gov.bd'),
            array('id' => '226','district_id' => '29','name' => 'Harinakundu','local_name' => 'হরিণাকুন্ডু','url' => 'harinakundu.jhenaidah.gov.bd'),
            array('id' => '227','district_id' => '29','name' => 'Kaliganj','local_name' => 'কালীগঞ্জ','url' => 'kaliganj.jhenaidah.gov.bd'),
            array('id' => '228','district_id' => '29','name' => 'Kotchandpur','local_name' => 'কোটচাঁদপুর','url' => 'kotchandpur.jhenaidah.gov.bd'),
            array('id' => '229','district_id' => '29','name' => 'Moheshpur','local_name' => 'মহেশপুর','url' => 'moheshpur.jhenaidah.gov.bd'),
            array('id' => '230','district_id' => '30','name' => 'Jhalakathi Sadar','local_name' => 'ঝালকাঠি সদর','url' => 'sadar.jhalakathi.gov.bd'),
            array('id' => '231','district_id' => '30','name' => 'Kathalia','local_name' => 'কাঠালিয়া','url' => 'kathalia.jhalakathi.gov.bd'),
            array('id' => '232','district_id' => '30','name' => 'Nalchity','local_name' => 'নলছিটি','url' => 'nalchity.jhalakathi.gov.bd'),
            array('id' => '233','district_id' => '30','name' => 'Rajapur','local_name' => 'রাজাপুর','url' => 'rajapur.jhalakathi.gov.bd'),
            array('id' => '234','district_id' => '31','name' => 'Bauphal','local_name' => 'বাউফল','url' => 'bauphal.patuakhali.gov.bd'),
            array('id' => '235','district_id' => '31','name' => 'Patuakhali Sadar','local_name' => 'পটুয়াখালী সদর','url' => 'sadar.patuakhali.gov.bd'),
            array('id' => '236','district_id' => '31','name' => 'Dumki','local_name' => 'দুমকি','url' => 'dumki.patuakhali.gov.bd'),
            array('id' => '237','district_id' => '31','name' => 'Dashmina','local_name' => 'দশমিনা','url' => 'dashmina.patuakhali.gov.bd'),
            array('id' => '238','district_id' => '31','name' => 'Kalapara','local_name' => 'কলাপাড়া','url' => 'kalapara.patuakhali.gov.bd'),
            array('id' => '239','district_id' => '31','name' => 'Mirzaganj','local_name' => 'মির্জাগঞ্জ','url' => 'mirzaganj.patuakhali.gov.bd'),
            array('id' => '240','district_id' => '31','name' => 'Galachipa','local_name' => 'গলাচিপা','url' => 'galachipa.patuakhali.gov.bd'),
            array('id' => '241','district_id' => '31','name' => 'Rangabali','local_name' => 'রাঙ্গাবালী','url' => 'rangabali.patuakhali.gov.bd'),
            array('id' => '242','district_id' => '32','name' => 'Pirojpur Sadar','local_name' => 'পিরোজপুর সদর','url' => 'sadar.pirojpur.gov.bd'),
            array('id' => '243','district_id' => '32','name' => 'Nazirpur','local_name' => 'নাজিরপুর','url' => 'nazirpur.pirojpur.gov.bd'),
            array('id' => '244','district_id' => '32','name' => 'Kawkhali','local_name' => 'কাউখালী','url' => 'kawkhali.pirojpur.gov.bd'),
            array('id' => '245','district_id' => '32','name' => 'Zianagar','local_name' => 'জিয়ানগর','url' => 'zianagar.pirojpur.gov.bd'),
            array('id' => '246','district_id' => '32','name' => 'Bhandaria','local_name' => 'ভান্ডারিয়া','url' => 'bhandaria.pirojpur.gov.bd'),
            array('id' => '247','district_id' => '32','name' => 'Mathbaria','local_name' => 'মঠবাড়ীয়া','url' => 'mathbaria.pirojpur.gov.bd'),
            array('id' => '248','district_id' => '32','name' => 'Nesarabad','local_name' => 'নেছারাবাদ','url' => 'nesarabad.pirojpur.gov.bd'),
            array('id' => '249','district_id' => '33','name' => 'Barisal Sadar','local_name' => 'বরিশাল সদর','url' => 'barisalsadar.barisal.gov.bd'),
            array('id' => '250','district_id' => '33','name' => 'Bakerganj','local_name' => 'বাকেরগঞ্জ','url' => 'bakerganj.barisal.gov.bd'),
            array('id' => '251','district_id' => '33','name' => 'Babuganj','local_name' => 'বাবুগঞ্জ','url' => 'babuganj.barisal.gov.bd'),
            array('id' => '252','district_id' => '33','name' => 'Wazirpur','local_name' => 'উজিরপুর','url' => 'wazirpur.barisal.gov.bd'),
            array('id' => '253','district_id' => '33','name' => 'Banaripara','local_name' => 'বানারীপাড়া','url' => 'banaripara.barisal.gov.bd'),
            array('id' => '254','district_id' => '33','name' => 'Gournadi','local_name' => 'গৌরনদী','url' => 'gournadi.barisal.gov.bd'),
            array('id' => '255','district_id' => '33','name' => 'Agailjhara','local_name' => 'আগৈলঝাড়া','url' => 'agailjhara.barisal.gov.bd'),
            array('id' => '256','district_id' => '33','name' => 'Mehendiganj','local_name' => 'মেহেন্দিগঞ্জ','url' => 'mehendiganj.barisal.gov.bd'),
            array('id' => '257','district_id' => '33','name' => 'Muladi','local_name' => 'মুলাদী','url' => 'muladi.barisal.gov.bd'),
            array('id' => '258','district_id' => '33','name' => 'Hizla','local_name' => 'হিজলা','url' => 'hizla.barisal.gov.bd'),
            array('id' => '259','district_id' => '34','name' => 'Bhola Sadar','local_name' => 'ভোলা সদর','url' => 'sadar.bhola.gov.bd'),
            array('id' => '260','district_id' => '34','name' => 'Borhan Sddin','local_name' => 'বোরহান উদ্দিন','url' => 'borhanuddin.bhola.gov.bd'),
            array('id' => '261','district_id' => '34','name' => 'Charfesson','local_name' => 'চরফ্যাশন','url' => 'charfesson.bhola.gov.bd'),
            array('id' => '262','district_id' => '34','name' => 'Doulatkhan','local_name' => 'দৌলতখান','url' => 'doulatkhan.bhola.gov.bd'),
            array('id' => '263','district_id' => '34','name' => 'Monpura','local_name' => 'মনপুরা','url' => 'monpura.bhola.gov.bd'),
            array('id' => '264','district_id' => '34','name' => 'Tazumuddin','local_name' => 'তজুমদ্দিন','url' => 'tazumuddin.bhola.gov.bd'),
            array('id' => '265','district_id' => '34','name' => 'Lalmohan','local_name' => 'লালমোহন','url' => 'lalmohan.bhola.gov.bd'),
            array('id' => '266','district_id' => '35','name' => 'Amtali','local_name' => 'আমতলী','url' => 'amtali.barguna.gov.bd'),
            array('id' => '267','district_id' => '35','name' => 'Barguna Sadar','local_name' => 'বরগুনা সদর','url' => 'sadar.barguna.gov.bd'),
            array('id' => '268','district_id' => '35','name' => 'Betagi','local_name' => 'বেতাগী','url' => 'betagi.barguna.gov.bd'),
            array('id' => '269','district_id' => '35','name' => 'Bamna','local_name' => 'বামনা','url' => 'bamna.barguna.gov.bd'),
            array('id' => '270','district_id' => '35','name' => 'Pathorghata','local_name' => 'পাথরঘাটা','url' => 'pathorghata.barguna.gov.bd'),
            array('id' => '271','district_id' => '35','name' => 'Taltali','local_name' => 'তালতলি','url' => 'taltali.barguna.gov.bd'),
            array('id' => '272','district_id' => '36','name' => 'Balaganj','local_name' => 'বালাগঞ্জ','url' => 'balaganj.sylhet.gov.bd'),
            array('id' => '273','district_id' => '36','name' => 'Beanibazar','local_name' => 'বিয়ানীবাজার','url' => 'beanibazar.sylhet.gov.bd'),
            array('id' => '274','district_id' => '36','name' => 'Bishwanath','local_name' => 'বিশ্বনাথ','url' => 'bishwanath.sylhet.gov.bd'),
            array('id' => '275','district_id' => '36','name' => 'Companiganj','local_name' => 'কোম্পানীগঞ্জ','url' => 'companiganj.sylhet.gov.bd'),
            array('id' => '276','district_id' => '36','name' => 'Fenchuganj','local_name' => 'ফেঞ্চুগঞ্জ','url' => 'fenchuganj.sylhet.gov.bd'),
            array('id' => '277','district_id' => '36','name' => 'Golapganj','local_name' => 'গোলাপগঞ্জ','url' => 'golapganj.sylhet.gov.bd'),
            array('id' => '278','district_id' => '36','name' => 'Gowainghat','local_name' => 'গোয়াইনঘাট','url' => 'gowainghat.sylhet.gov.bd'),
            array('id' => '279','district_id' => '36','name' => 'Jaintiapur','local_name' => 'জৈন্তাপুর','url' => 'jaintiapur.sylhet.gov.bd'),
            array('id' => '280','district_id' => '36','name' => 'Kanaighat','local_name' => 'কানাইঘাট','url' => 'kanaighat.sylhet.gov.bd'),
            array('id' => '281','district_id' => '36','name' => 'Sylhet Sadar','local_name' => 'সিলেট সদর','url' => 'sylhetsadar.sylhet.gov.bd'),
            array('id' => '282','district_id' => '36','name' => 'Zakiganj','local_name' => 'জকিগঞ্জ','url' => 'zakiganj.sylhet.gov.bd'),
            array('id' => '283','district_id' => '36','name' => 'Dakshinsurma','local_name' => 'দক্ষিণ সুরমা','url' => 'dakshinsurma.sylhet.gov.bd'),
            array('id' => '284','district_id' => '36','name' => 'Osmaninagar','local_name' => 'ওসমানী নগর','url' => 'osmaninagar.sylhet.gov.bd'),
            array('id' => '285','district_id' => '37','name' => 'Barlekha','local_name' => 'বড়লেখা','url' => 'barlekha.moulvibazar.gov.bd'),
            array('id' => '286','district_id' => '37','name' => 'Kamolganj','local_name' => 'কমলগঞ্জ','url' => 'kamolganj.moulvibazar.gov.bd'),
            array('id' => '287','district_id' => '37','name' => 'Kulaura','local_name' => 'কুলাউড়া','url' => 'kulaura.moulvibazar.gov.bd'),
            array('id' => '288','district_id' => '37','name' => 'Moulvibazar Sadar','local_name' => 'মৌলভীবাজার সদর','url' => 'moulvibazarsadar.moulvibazar.gov.bd'),
            array('id' => '289','district_id' => '37','name' => 'Rajnagar','local_name' => 'রাজনগর','url' => 'rajnagar.moulvibazar.gov.bd'),
            array('id' => '290','district_id' => '37','name' => 'Sreemangal','local_name' => 'শ্রীমঙ্গল','url' => 'sreemangal.moulvibazar.gov.bd'),
            array('id' => '291','district_id' => '37','name' => 'Juri','local_name' => 'জুড়ী','url' => 'juri.moulvibazar.gov.bd'),
            array('id' => '292','district_id' => '38','name' => 'Nabiganj','local_name' => 'নবীগঞ্জ','url' => 'nabiganj.habiganj.gov.bd'),
            array('id' => '293','district_id' => '38','name' => 'Bahubal','local_name' => 'বাহুবল','url' => 'bahubal.habiganj.gov.bd'),
            array('id' => '294','district_id' => '38','name' => 'Ajmiriganj','local_name' => 'আজমিরীগঞ্জ','url' => 'ajmiriganj.habiganj.gov.bd'),
            array('id' => '295','district_id' => '38','name' => 'Baniachong','local_name' => 'বানিয়াচং','url' => 'baniachong.habiganj.gov.bd'),
            array('id' => '296','district_id' => '38','name' => 'Lakhai','local_name' => 'লাখাই','url' => 'lakhai.habiganj.gov.bd'),
            array('id' => '297','district_id' => '38','name' => 'Chunarughat','local_name' => 'চুনারুঘাট','url' => 'chunarughat.habiganj.gov.bd'),
            array('id' => '298','district_id' => '38','name' => 'Habiganj Sadar','local_name' => 'হবিগঞ্জ সদর','url' => 'habiganjsadar.habiganj.gov.bd'),
            array('id' => '299','district_id' => '38','name' => 'Madhabpur','local_name' => 'মাধবপুর','url' => 'madhabpur.habiganj.gov.bd'),
            array('id' => '300','district_id' => '39','name' => 'Sunamganj Sadar','local_name' => 'সুনামগঞ্জ সদর','url' => 'sadar.sunamganj.gov.bd'),
            array('id' => '301','district_id' => '39','name' => 'South Sunamganj','local_name' => 'দক্ষিণ সুনামগঞ্জ','url' => 'southsunamganj.sunamganj.gov.bd'),
            array('id' => '302','district_id' => '39','name' => 'Bishwambarpur','local_name' => 'বিশ্বম্ভরপুর','url' => 'bishwambarpur.sunamganj.gov.bd'),
            array('id' => '303','district_id' => '39','name' => 'Chhatak','local_name' => 'ছাতক','url' => 'chhatak.sunamganj.gov.bd'),
            array('id' => '304','district_id' => '39','name' => 'Jagannathpur','local_name' => 'জগন্নাথপুর','url' => 'jagannathpur.sunamganj.gov.bd'),
            array('id' => '305','district_id' => '39','name' => 'Dowarabazar','local_name' => 'দোয়ারাবাজার','url' => 'dowarabazar.sunamganj.gov.bd'),
            array('id' => '306','district_id' => '39','name' => 'Tahirpur','local_name' => 'তাহিরপুর','url' => 'tahirpur.sunamganj.gov.bd'),
            array('id' => '307','district_id' => '39','name' => 'Dharmapasha','local_name' => 'ধর্মপাশা','url' => 'dharmapasha.sunamganj.gov.bd'),
            array('id' => '308','district_id' => '39','name' => 'Jamalganj','local_name' => 'জামালগঞ্জ','url' => 'jamalganj.sunamganj.gov.bd'),
            array('id' => '309','district_id' => '39','name' => 'Shalla','local_name' => 'শাল্লা','url' => 'shalla.sunamganj.gov.bd'),
            array('id' => '310','district_id' => '39','name' => 'Derai','local_name' => 'দিরাই','url' => 'derai.sunamganj.gov.bd'),
            array('id' => '311','district_id' => '40','name' => 'Belabo','local_name' => 'বেলাবো','url' => 'belabo.narsingdi.gov.bd'),
            array('id' => '312','district_id' => '40','name' => 'Monohardi','local_name' => 'মনোহরদী','url' => 'monohardi.narsingdi.gov.bd'),
            array('id' => '313','district_id' => '40','name' => 'Narsingdi Sadar','local_name' => 'নরসিংদী সদর','url' => 'narsingdisadar.narsingdi.gov.bd'),
            array('id' => '314','district_id' => '40','name' => 'Palash','local_name' => 'পলাশ','url' => 'palash.narsingdi.gov.bd'),
            array('id' => '315','district_id' => '40','name' => 'Raipura','local_name' => 'রায়পুরা','url' => 'raipura.narsingdi.gov.bd'),
            array('id' => '316','district_id' => '40','name' => 'Shibpur','local_name' => 'শিবপুর','url' => 'shibpur.narsingdi.gov.bd'),
            array('id' => '317','district_id' => '41','name' => 'Kaliganj','local_name' => 'কালীগঞ্জ','url' => 'kaliganj.gazipur.gov.bd'),
            array('id' => '318','district_id' => '41','name' => 'Kaliakair','local_name' => 'কালিয়াকৈর','url' => 'kaliakair.gazipur.gov.bd'),
            array('id' => '319','district_id' => '41','name' => 'Kapasia','local_name' => 'কাপাসিয়া','url' => 'kapasia.gazipur.gov.bd'),
            array('id' => '320','district_id' => '41','name' => 'Gazipur Sadar','local_name' => 'গাজীপুর সদর','url' => 'sadar.gazipur.gov.bd'),
            array('id' => '321','district_id' => '41','name' => 'Sreepur','local_name' => 'শ্রীপুর','url' => 'sreepur.gazipur.gov.bd'),
            array('id' => '322','district_id' => '42','name' => 'Shariatpur Sadar','local_name' => 'শরিয়তপুর সদর','url' => 'sadar.shariatpur.gov.bd'),
            array('id' => '323','district_id' => '42','name' => 'Naria','local_name' => 'নড়িয়া','url' => 'naria.shariatpur.gov.bd'),
            array('id' => '324','district_id' => '42','name' => 'Zajira','local_name' => 'জাজিরা','url' => 'zajira.shariatpur.gov.bd'),
            array('id' => '325','district_id' => '42','name' => 'Gosairhat','local_name' => 'গোসাইরহাট','url' => 'gosairhat.shariatpur.gov.bd'),
            array('id' => '326','district_id' => '42','name' => 'Bhedarganj','local_name' => 'ভেদরগঞ্জ','url' => 'bhedarganj.shariatpur.gov.bd'),
            array('id' => '327','district_id' => '42','name' => 'Damudya','local_name' => 'ডামুড্যা','url' => 'damudya.shariatpur.gov.bd'),
            array('id' => '328','district_id' => '43','name' => 'Araihazar','local_name' => 'আড়াইহাজার','url' => 'araihazar.narayanganj.gov.bd'),
            array('id' => '329','district_id' => '43','name' => 'Bandar','local_name' => 'বন্দর','url' => 'bandar.narayanganj.gov.bd'),
            array('id' => '330','district_id' => '43','name' => 'Narayanganj Sadar','local_name' => 'নারায়নগঞ্জ সদর','url' => 'narayanganjsadar.narayanganj.gov.bd'),
            array('id' => '331','district_id' => '43','name' => 'Rupganj','local_name' => 'রূপগঞ্জ','url' => 'rupganj.narayanganj.gov.bd'),
            array('id' => '332','district_id' => '43','name' => 'Sonargaon','local_name' => 'সোনারগাঁ','url' => 'sonargaon.narayanganj.gov.bd'),
            array('id' => '333','district_id' => '44','name' => 'Basail','local_name' => 'বাসাইল','url' => 'basail.tangail.gov.bd'),
            array('id' => '334','district_id' => '44','name' => 'Bhuapur','local_name' => 'ভুয়াপুর','url' => 'bhuapur.tangail.gov.bd'),
            array('id' => '335','district_id' => '44','name' => 'Delduar','local_name' => 'দেলদুয়ার','url' => 'delduar.tangail.gov.bd'),
            array('id' => '336','district_id' => '44','name' => 'Ghatail','local_name' => 'ঘাটাইল','url' => 'ghatail.tangail.gov.bd'),
            array('id' => '337','district_id' => '44','name' => 'Gopalpur','local_name' => 'গোপালপুর','url' => 'gopalpur.tangail.gov.bd'),
            array('id' => '338','district_id' => '44','name' => 'Madhupur','local_name' => 'মধুপুর','url' => 'madhupur.tangail.gov.bd'),
            array('id' => '339','district_id' => '44','name' => 'Mirzapur','local_name' => 'মির্জাপুর','url' => 'mirzapur.tangail.gov.bd'),
            array('id' => '340','district_id' => '44','name' => 'Nagarpur','local_name' => 'নাগরপুর','url' => 'nagarpur.tangail.gov.bd'),
            array('id' => '341','district_id' => '44','name' => 'Sakhipur','local_name' => 'সখিপুর','url' => 'sakhipur.tangail.gov.bd'),
            array('id' => '342','district_id' => '44','name' => 'Tangail Sadar','local_name' => 'টাঙ্গাইল সদর','url' => 'tangailsadar.tangail.gov.bd'),
            array('id' => '343','district_id' => '44','name' => 'Kalihati','local_name' => 'কালিহাতী','url' => 'kalihati.tangail.gov.bd'),
            array('id' => '344','district_id' => '44','name' => 'Dhanbari','local_name' => 'ধনবাড়ী','url' => 'dhanbari.tangail.gov.bd'),
            array('id' => '345','district_id' => '45','name' => 'Itna','local_name' => 'ইটনা','url' => 'itna.kishoreganj.gov.bd'),
            array('id' => '346','district_id' => '45','name' => 'Katiadi','local_name' => 'কটিয়াদী','url' => 'katiadi.kishoreganj.gov.bd'),
            array('id' => '347','district_id' => '45','name' => 'Bhairab','local_name' => 'ভৈরব','url' => 'bhairab.kishoreganj.gov.bd'),
            array('id' => '348','district_id' => '45','name' => 'Tarail','local_name' => 'তাড়াইল','url' => 'tarail.kishoreganj.gov.bd'),
            array('id' => '349','district_id' => '45','name' => 'Hossainpur','local_name' => 'হোসেনপুর','url' => 'hossainpur.kishoreganj.gov.bd'),
            array('id' => '350','district_id' => '45','name' => 'Pakundia','local_name' => 'পাকুন্দিয়া','url' => 'pakundia.kishoreganj.gov.bd'),
            array('id' => '351','district_id' => '45','name' => 'Kuliarchar','local_name' => 'কুলিয়ারচর','url' => 'kuliarchar.kishoreganj.gov.bd'),
            array('id' => '352','district_id' => '45','name' => 'Kishoreganj Sadar','local_name' => 'কিশোরগঞ্জ সদর','url' => 'kishoreganjsadar.kishoreganj.gov.bd'),
            array('id' => '353','district_id' => '45','name' => 'Karimgonj','local_name' => 'করিমগঞ্জ','url' => 'karimgonj.kishoreganj.gov.bd'),
            array('id' => '354','district_id' => '45','name' => 'Bajitpur','local_name' => 'বাজিতপুর','url' => 'bajitpur.kishoreganj.gov.bd'),
            array('id' => '355','district_id' => '45','name' => 'Austagram','local_name' => 'অষ্টগ্রাম','url' => 'austagram.kishoreganj.gov.bd'),
            array('id' => '356','district_id' => '45','name' => 'Mithamoin','local_name' => 'মিঠামইন','url' => 'mithamoin.kishoreganj.gov.bd'),
            array('id' => '357','district_id' => '45','name' => 'Nikli','local_name' => 'নিকলী','url' => 'nikli.kishoreganj.gov.bd'),
            array('id' => '358','district_id' => '46','name' => 'Harirampur','local_name' => 'হরিরামপুর','url' => 'harirampur.manikganj.gov.bd'),
            array('id' => '359','district_id' => '46','name' => 'Saturia','local_name' => 'সাটুরিয়া','url' => 'saturia.manikganj.gov.bd'),
            array('id' => '360','district_id' => '46','name' => 'Manikganj Sadar','local_name' => 'মানিকগঞ্জ সদর','url' => 'sadar.manikganj.gov.bd'),
            array('id' => '361','district_id' => '46','name' => 'Gior','local_name' => 'ঘিওর','url' => 'gior.manikganj.gov.bd'),
            array('id' => '362','district_id' => '46','name' => 'Shibaloy','local_name' => 'শিবালয়','url' => 'shibaloy.manikganj.gov.bd'),
            array('id' => '363','district_id' => '46','name' => 'Doulatpur','local_name' => 'দৌলতপুর','url' => 'doulatpur.manikganj.gov.bd'),
            array('id' => '364','district_id' => '46','name' => 'Singiar','local_name' => 'সিংগাইর','url' => 'singiar.manikganj.gov.bd'),
            array('id' => '365','district_id' => '47','name' => 'Savar','local_name' => 'সাভার','url' => 'savar.dhaka.gov.bd'),
            array('id' => '366','district_id' => '47','name' => 'Dhamrai','local_name' => 'ধামরাই','url' => 'dhamrai.dhaka.gov.bd'),
            array('id' => '367','district_id' => '47','name' => 'Keraniganj','local_name' => 'কেরাণীগঞ্জ','url' => 'keraniganj.dhaka.gov.bd'),
            array('id' => '368','district_id' => '47','name' => 'Nawabganj','local_name' => 'নবাবগঞ্জ','url' => 'nawabganj.dhaka.gov.bd'),
            array('id' => '369','district_id' => '47','name' => 'Dohar','local_name' => 'দোহার','url' => 'dohar.dhaka.gov.bd'),
            array('id' => '370','district_id' => '48','name' => 'Munshiganj Sadar','local_name' => 'মুন্সিগঞ্জ সদর','url' => 'sadar.munshiganj.gov.bd'),
            array('id' => '371','district_id' => '48','name' => 'Sreenagar','local_name' => 'শ্রীনগর','url' => 'sreenagar.munshiganj.gov.bd'),
            array('id' => '372','district_id' => '48','name' => 'Sirajdikhan','local_name' => 'সিরাজদিখান','url' => 'sirajdikhan.munshiganj.gov.bd'),
            array('id' => '373','district_id' => '48','name' => 'Louhajanj','local_name' => 'লৌহজং','url' => 'louhajanj.munshiganj.gov.bd'),
            array('id' => '374','district_id' => '48','name' => 'Gajaria','local_name' => 'গজারিয়া','url' => 'gajaria.munshiganj.gov.bd'),
            array('id' => '375','district_id' => '48','name' => 'Tongibari','local_name' => 'টংগীবাড়ি','url' => 'tongibari.munshiganj.gov.bd'),
            array('id' => '376','district_id' => '49','name' => 'Rajbari Sadar','local_name' => 'রাজবাড়ী সদর','url' => 'sadar.rajbari.gov.bd'),
            array('id' => '377','district_id' => '49','name' => 'Goalanda','local_name' => 'গোয়ালন্দ','url' => 'goalanda.rajbari.gov.bd'),
            array('id' => '378','district_id' => '49','name' => 'Pangsa','local_name' => 'পাংশা','url' => 'pangsa.rajbari.gov.bd'),
            array('id' => '379','district_id' => '49','name' => 'Baliakandi','local_name' => 'বালিয়াকান্দি','url' => 'baliakandi.rajbari.gov.bd'),
            array('id' => '380','district_id' => '49','name' => 'Kalukhali','local_name' => 'কালুখালী','url' => 'kalukhali.rajbari.gov.bd'),
            array('id' => '381','district_id' => '50','name' => 'Madaripur Sadar','local_name' => 'মাদারীপুর সদর','url' => 'sadar.madaripur.gov.bd'),
            array('id' => '382','district_id' => '50','name' => 'Shibchar','local_name' => 'শিবচর','url' => 'shibchar.madaripur.gov.bd'),
            array('id' => '383','district_id' => '50','name' => 'Kalkini','local_name' => 'কালকিনি','url' => 'kalkini.madaripur.gov.bd'),
            array('id' => '384','district_id' => '50','name' => 'Rajoir','local_name' => 'রাজৈর','url' => 'rajoir.madaripur.gov.bd'),
            array('id' => '385','district_id' => '51','name' => 'Gopalganj Sadar','local_name' => 'গোপালগঞ্জ সদর','url' => 'sadar.gopalganj.gov.bd'),
            array('id' => '386','district_id' => '51','name' => 'Kashiani','local_name' => 'কাশিয়ানী','url' => 'kashiani.gopalganj.gov.bd'),
            array('id' => '387','district_id' => '51','name' => 'Tungipara','local_name' => 'টুংগীপাড়া','url' => 'tungipara.gopalganj.gov.bd'),
            array('id' => '388','district_id' => '51','name' => 'Kotalipara','local_name' => 'কোটালীপাড়া','url' => 'kotalipara.gopalganj.gov.bd'),
            array('id' => '389','district_id' => '51','name' => 'Muksudpur','local_name' => 'মুকসুদপুর','url' => 'muksudpur.gopalganj.gov.bd'),
            array('id' => '390','district_id' => '52','name' => 'Faridpur Sadar','local_name' => 'ফরিদপুর সদর','url' => 'sadar.faridpur.gov.bd'),
            array('id' => '391','district_id' => '52','name' => 'Alfadanga','local_name' => 'আলফাডাঙ্গা','url' => 'alfadanga.faridpur.gov.bd'),
            array('id' => '392','district_id' => '52','name' => 'Boalmari','local_name' => 'বোয়ালমারী','url' => 'boalmari.faridpur.gov.bd'),
            array('id' => '393','district_id' => '52','name' => 'Sadarpur','local_name' => 'সদরপুর','url' => 'sadarpur.faridpur.gov.bd'),
            array('id' => '394','district_id' => '52','name' => 'Nagarkanda','local_name' => 'নগরকান্দা','url' => 'nagarkanda.faridpur.gov.bd'),
            array('id' => '395','district_id' => '52','name' => 'Bhanga','local_name' => 'ভাঙ্গা','url' => 'bhanga.faridpur.gov.bd'),
            array('id' => '396','district_id' => '52','name' => 'Charbhadrasan','local_name' => 'চরভদ্রাসন','url' => 'charbhadrasan.faridpur.gov.bd'),
            array('id' => '397','district_id' => '52','name' => 'Madhukhali','local_name' => 'মধুখালী','url' => 'madhukhali.faridpur.gov.bd'),
            array('id' => '398','district_id' => '52','name' => 'Saltha','local_name' => 'সালথা','url' => 'saltha.faridpur.gov.bd'),
            array('id' => '399','district_id' => '53','name' => 'Panchagarh Sadar','local_name' => 'পঞ্চগড় সদর','url' => 'panchagarhsadar.panchagarh.gov.bd'),
            array('id' => '400','district_id' => '53','name' => 'Debiganj','local_name' => 'দেবীগঞ্জ','url' => 'debiganj.panchagarh.gov.bd'),
            array('id' => '401','district_id' => '53','name' => 'Boda','local_name' => 'বোদা','url' => 'boda.panchagarh.gov.bd'),
            array('id' => '402','district_id' => '53','name' => 'Atwari','local_name' => 'আটোয়ারী','url' => 'atwari.panchagarh.gov.bd'),
            array('id' => '403','district_id' => '53','name' => 'Tetulia','local_name' => 'তেতুলিয়া','url' => 'tetulia.panchagarh.gov.bd'),
            array('id' => '404','district_id' => '54','name' => 'Nawabganj','local_name' => 'নবাবগঞ্জ','url' => 'nawabganj.dinajpur.gov.bd'),
            array('id' => '405','district_id' => '54','name' => 'Birganj','local_name' => 'বীরগঞ্জ','url' => 'birganj.dinajpur.gov.bd'),
            array('id' => '406','district_id' => '54','name' => 'Ghoraghat','local_name' => 'ঘোড়াঘাট','url' => 'ghoraghat.dinajpur.gov.bd'),
            array('id' => '407','district_id' => '54','name' => 'Birampur','local_name' => 'বিরামপুর','url' => 'birampur.dinajpur.gov.bd'),
            array('id' => '408','district_id' => '54','name' => 'Parbatipur','local_name' => 'পার্বতীপুর','url' => 'parbatipur.dinajpur.gov.bd'),
            array('id' => '409','district_id' => '54','name' => 'Bochaganj','local_name' => 'বোচাগঞ্জ','url' => 'bochaganj.dinajpur.gov.bd'),
            array('id' => '410','district_id' => '54','name' => 'Kaharol','local_name' => 'কাহারোল','url' => 'kaharol.dinajpur.gov.bd'),
            array('id' => '411','district_id' => '54','name' => 'Fulbari','local_name' => 'ফুলবাড়ী','url' => 'fulbari.dinajpur.gov.bd'),
            array('id' => '412','district_id' => '54','name' => 'Dinajpur Sadar','local_name' => 'দিনাজপুর সদর','url' => 'dinajpursadar.dinajpur.gov.bd'),
            array('id' => '413','district_id' => '54','name' => 'Hakimpur','local_name' => 'হাকিমপুর','url' => 'hakimpur.dinajpur.gov.bd'),
            array('id' => '414','district_id' => '54','name' => 'Khansama','local_name' => 'খানসামা','url' => 'khansama.dinajpur.gov.bd'),
            array('id' => '415','district_id' => '54','name' => 'Birol','local_name' => 'বিরল','url' => 'birol.dinajpur.gov.bd'),
            array('id' => '416','district_id' => '54','name' => 'Chirirbandar','local_name' => 'চিরিরবন্দর','url' => 'chirirbandar.dinajpur.gov.bd'),
            array('id' => '417','district_id' => '55','name' => 'Lalmonirhat Sadar','local_name' => 'লালমনিরহাট সদর','url' => 'sadar.lalmonirhat.gov.bd'),
            array('id' => '418','district_id' => '55','name' => 'Kaliganj','local_name' => 'কালীগঞ্জ','url' => 'kaliganj.lalmonirhat.gov.bd'),
            array('id' => '419','district_id' => '55','name' => 'Hatibandha','local_name' => 'হাতীবান্ধা','url' => 'hatibandha.lalmonirhat.gov.bd'),
            array('id' => '420','district_id' => '55','name' => 'Patgram','local_name' => 'পাটগ্রাম','url' => 'patgram.lalmonirhat.gov.bd'),
            array('id' => '421','district_id' => '55','name' => 'Aditmari','local_name' => 'আদিতমারী','url' => 'aditmari.lalmonirhat.gov.bd'),
            array('id' => '422','district_id' => '56','name' => 'Syedpur','local_name' => 'সৈয়দপুর','url' => 'syedpur.nilphamari.gov.bd'),
            array('id' => '423','district_id' => '56','name' => 'Domar','local_name' => 'ডোমার','url' => 'domar.nilphamari.gov.bd'),
            array('id' => '424','district_id' => '56','name' => 'Dimla','local_name' => 'ডিমলা','url' => 'dimla.nilphamari.gov.bd'),
            array('id' => '425','district_id' => '56','name' => 'Jaldhaka','local_name' => 'জলঢাকা','url' => 'jaldhaka.nilphamari.gov.bd'),
            array('id' => '426','district_id' => '56','name' => 'Kishorganj','local_name' => 'কিশোরগঞ্জ','url' => 'kishorganj.nilphamari.gov.bd'),
            array('id' => '427','district_id' => '56','name' => 'Nilphamari Sadar','local_name' => 'নীলফামারী সদর','url' => 'nilphamarisadar.nilphamari.gov.bd'),
            array('id' => '428','district_id' => '57','name' => 'Sadullapur','local_name' => 'সাদুল্লাপুর','url' => 'sadullapur.gaibandha.gov.bd'),
            array('id' => '429','district_id' => '57','name' => 'Gaibandha Sadar','local_name' => 'গাইবান্ধা সদর','url' => 'gaibandhasadar.gaibandha.gov.bd'),
            array('id' => '430','district_id' => '57','name' => 'Palashbari','local_name' => 'পলাশবাড়ী','url' => 'palashbari.gaibandha.gov.bd'),
            array('id' => '431','district_id' => '57','name' => 'Saghata','local_name' => 'সাঘাটা','url' => 'saghata.gaibandha.gov.bd'),
            array('id' => '432','district_id' => '57','name' => 'Gobindaganj','local_name' => 'গোবিন্দগঞ্জ','url' => 'gobindaganj.gaibandha.gov.bd'),
            array('id' => '433','district_id' => '57','name' => 'Sundarganj','local_name' => 'সুন্দরগঞ্জ','url' => 'sundarganj.gaibandha.gov.bd'),
            array('id' => '434','district_id' => '57','name' => 'Phulchari','local_name' => 'ফুলছড়ি','url' => 'phulchari.gaibandha.gov.bd'),
            array('id' => '435','district_id' => '58','name' => 'Thakurgaon Sadar','local_name' => 'ঠাকুরগাঁও সদর','url' => 'thakurgaonsadar.thakurgaon.gov.bd'),
            array('id' => '436','district_id' => '58','name' => 'Pirganj','local_name' => 'পীরগঞ্জ','url' => 'pirganj.thakurgaon.gov.bd'),
            array('id' => '437','district_id' => '58','name' => 'Ranisankail','local_name' => 'রাণীশংকৈল','url' => 'ranisankail.thakurgaon.gov.bd'),
            array('id' => '438','district_id' => '58','name' => 'Haripur','local_name' => 'হরিপুর','url' => 'haripur.thakurgaon.gov.bd'),
            array('id' => '439','district_id' => '58','name' => 'Baliadangi','local_name' => 'বালিয়াডাঙ্গী','url' => 'baliadangi.thakurgaon.gov.bd'),
            array('id' => '440','district_id' => '59','name' => 'Rangpur Sadar','local_name' => 'রংপুর সদর','url' => 'rangpursadar.rangpur.gov.bd'),
            array('id' => '441','district_id' => '59','name' => 'Gangachara','local_name' => 'গংগাচড়া','url' => 'gangachara.rangpur.gov.bd'),
            array('id' => '442','district_id' => '59','name' => 'Taragonj','local_name' => 'তারাগঞ্জ','url' => 'taragonj.rangpur.gov.bd'),
            array('id' => '443','district_id' => '59','name' => 'Badargonj','local_name' => 'বদরগঞ্জ','url' => 'badargonj.rangpur.gov.bd'),
            array('id' => '444','district_id' => '59','name' => 'Mithapukur','local_name' => 'মিঠাপুকুর','url' => 'mithapukur.rangpur.gov.bd'),
            array('id' => '445','district_id' => '59','name' => 'Pirgonj','local_name' => 'পীরগঞ্জ','url' => 'pirgonj.rangpur.gov.bd'),
            array('id' => '446','district_id' => '59','name' => 'Kaunia','local_name' => 'কাউনিয়া','url' => 'kaunia.rangpur.gov.bd'),
            array('id' => '447','district_id' => '59','name' => 'Pirgacha','local_name' => 'পীরগাছা','url' => 'pirgacha.rangpur.gov.bd'),
            array('id' => '448','district_id' => '60','name' => 'Kurigram Sadar','local_name' => 'কুড়িগ্রাম সদর','url' => 'kurigramsadar.kurigram.gov.bd'),
            array('id' => '449','district_id' => '60','name' => 'Nageshwari','local_name' => 'নাগেশ্বরী','url' => 'nageshwari.kurigram.gov.bd'),
            array('id' => '450','district_id' => '60','name' => 'Bhurungamari','local_name' => 'ভুরুঙ্গামারী','url' => 'bhurungamari.kurigram.gov.bd'),
            array('id' => '451','district_id' => '60','name' => 'Phulbari','local_name' => 'ফুলবাড়ী','url' => 'phulbari.kurigram.gov.bd'),
            array('id' => '452','district_id' => '60','name' => 'Rajarhat','local_name' => 'রাজারহাট','url' => 'rajarhat.kurigram.gov.bd'),
            array('id' => '453','district_id' => '60','name' => 'Ulipur','local_name' => 'উলিপুর','url' => 'ulipur.kurigram.gov.bd'),
            array('id' => '454','district_id' => '60','name' => 'Chilmari','local_name' => 'চিলমারী','url' => 'chilmari.kurigram.gov.bd'),
            array('id' => '455','district_id' => '60','name' => 'Rowmari','local_name' => 'রৌমারী','url' => 'rowmari.kurigram.gov.bd'),
            array('id' => '456','district_id' => '60','name' => 'Charrajibpur','local_name' => 'চর রাজিবপুর','url' => 'charrajibpur.kurigram.gov.bd'),
            array('id' => '457','district_id' => '61','name' => 'Sherpur Sadar','local_name' => 'শেরপুর সদর','url' => 'sherpursadar.sherpur.gov.bd'),
            array('id' => '458','district_id' => '61','name' => 'Nalitabari','local_name' => 'নালিতাবাড়ী','url' => 'nalitabari.sherpur.gov.bd'),
            array('id' => '459','district_id' => '61','name' => 'Sreebordi','local_name' => 'শ্রীবরদী','url' => 'sreebordi.sherpur.gov.bd'),
            array('id' => '460','district_id' => '61','name' => 'Nokla','local_name' => 'নকলা','url' => 'nokla.sherpur.gov.bd'),
            array('id' => '461','district_id' => '61','name' => 'Jhenaigati','local_name' => 'ঝিনাইগাতী','url' => 'jhenaigati.sherpur.gov.bd'),
            array('id' => '462','district_id' => '62','name' => 'Fulbaria','local_name' => 'ফুলবাড়ীয়া','url' => 'fulbaria.mymensingh.gov.bd'),
            array('id' => '463','district_id' => '62','name' => 'Trishal','local_name' => 'ত্রিশাল','url' => 'trishal.mymensingh.gov.bd'),
            array('id' => '464','district_id' => '62','name' => 'Bhaluka','local_name' => 'ভালুকা','url' => 'bhaluka.mymensingh.gov.bd'),
            array('id' => '465','district_id' => '62','name' => 'Muktagacha','local_name' => 'মুক্তাগাছা','url' => 'muktagacha.mymensingh.gov.bd'),
            array('id' => '466','district_id' => '62','name' => 'Mymensingh Sadar','local_name' => 'ময়মনসিংহ সদর','url' => 'mymensinghsadar.mymensingh.gov.bd'),
            array('id' => '467','district_id' => '62','name' => 'Dhobaura','local_name' => 'ধোবাউড়া','url' => 'dhobaura.mymensingh.gov.bd'),
            array('id' => '468','district_id' => '62','name' => 'Phulpur','local_name' => 'ফুলপুর','url' => 'phulpur.mymensingh.gov.bd'),
            array('id' => '469','district_id' => '62','name' => 'Haluaghat','local_name' => 'হালুয়াঘাট','url' => 'haluaghat.mymensingh.gov.bd'),
            array('id' => '470','district_id' => '62','name' => 'Gouripur','local_name' => 'গৌরীপুর','url' => 'gouripur.mymensingh.gov.bd'),
            array('id' => '471','district_id' => '62','name' => 'Gafargaon','local_name' => 'গফরগাঁও','url' => 'gafargaon.mymensingh.gov.bd'),
            array('id' => '472','district_id' => '62','name' => 'Iswarganj','local_name' => 'ঈশ্বরগঞ্জ','url' => 'iswarganj.mymensingh.gov.bd'),
            array('id' => '473','district_id' => '62','name' => 'Nandail','local_name' => 'নান্দাইল','url' => 'nandail.mymensingh.gov.bd'),
            array('id' => '474','district_id' => '62','name' => 'Tarakanda','local_name' => 'তারাকান্দা','url' => 'tarakanda.mymensingh.gov.bd'),
            array('id' => '475','district_id' => '63','name' => 'Jamalpur Sadar','local_name' => 'জামালপুর সদর','url' => 'jamalpursadar.jamalpur.gov.bd'),
            array('id' => '476','district_id' => '63','name' => 'Melandah','local_name' => 'মেলান্দহ','url' => 'melandah.jamalpur.gov.bd'),
            array('id' => '477','district_id' => '63','name' => 'Islampur','local_name' => 'ইসলামপুর','url' => 'islampur.jamalpur.gov.bd'),
            array('id' => '478','district_id' => '63','name' => 'Dewangonj','local_name' => 'দেওয়ানগঞ্জ','url' => 'dewangonj.jamalpur.gov.bd'),
            array('id' => '479','district_id' => '63','name' => 'Sarishabari','local_name' => 'সরিষাবাড়ী','url' => 'sarishabari.jamalpur.gov.bd'),
            array('id' => '480','district_id' => '63','name' => 'Madarganj','local_name' => 'মাদারগঞ্জ','url' => 'madarganj.jamalpur.gov.bd'),
            array('id' => '481','district_id' => '63','name' => 'Bokshiganj','local_name' => 'বকশীগঞ্জ','url' => 'bokshiganj.jamalpur.gov.bd'),
            array('id' => '482','district_id' => '64','name' => 'Barhatta','local_name' => 'বারহাট্টা','url' => 'barhatta.netrokona.gov.bd'),
            array('id' => '483','district_id' => '64','name' => 'Durgapur','local_name' => 'দুর্গাপুর','url' => 'durgapur.netrokona.gov.bd'),
            array('id' => '484','district_id' => '64','name' => 'Kendua','local_name' => 'কেন্দুয়া','url' => 'kendua.netrokona.gov.bd'),
            array('id' => '485','district_id' => '64','name' => 'Atpara','local_name' => 'আটপাড়া','url' => 'atpara.netrokona.gov.bd'),
            array('id' => '486','district_id' => '64','name' => 'Madan','local_name' => 'মদন','url' => 'madan.netrokona.gov.bd'),
            array('id' => '487','district_id' => '64','name' => 'Khaliajuri','local_name' => 'খালিয়াজুরী','url' => 'khaliajuri.netrokona.gov.bd'),
            array('id' => '488','district_id' => '64','name' => 'Kalmakanda','local_name' => 'কলমাকান্দা','url' => 'kalmakanda.netrokona.gov.bd'),
            array('id' => '489','district_id' => '64','name' => 'Mohongonj','local_name' => 'মোহনগঞ্জ','url' => 'mohongonj.netrokona.gov.bd'),
            array('id' => '490','district_id' => '64','name' => 'Purbadhala','local_name' => 'পূর্বধলা','url' => 'purbadhala.netrokona.gov.bd'),
            array('id' => '491','district_id' => '64','name' => 'Netrokona Sadar','local_name' => 'নেত্রকোণা সদর','url' => 'netrokonasadar.netrokona.gov.bd'),
            array('id' => '492','district_id' => '47','name' => 'Mirpur','local_name' => 'মিরপুর','url' => 'mirpur.dhaka.gov.bd'),
            array('id' => '493','district_id' => '47','name' => 'Mohammadpur','local_name' => 'মোহাম্মদপুর','url' => 'mohammadpur.dhaka.gov.bd'),
            array('id' => '494','district_id' => '47','name' => 'Dhanmondi','local_name' => 'ধানমন্ডি','url' => 'dhanmondi.dhaka.gov.bd'),
            array('id' => '495','district_id' => '47','name' => 'Gulshan','local_name' => 'গুলশান','url' => 'gulshan.dhaka.gov.bd'),
            array('id' => '496','district_id' => '47','name' => 'Tejgaon','local_name' => 'তেজগাঁও','url' => 'tejgaon.dhaka.gov.bd'),
            array('id' => '497','district_id' => '47','name' => 'Badda','local_name' => 'বাড্ডা','url' => 'badda.dhaka.gov.bd'),
            array('id' => '498','district_id' => '47','name' => 'Khilgaon','local_name' => 'খিলগাঁও','url' => 'khilgaon.dhaka.gov.bd'),
            array('id' => '502','district_id' => '47','name' => 'Rampura','local_name' => 'রামপুরা','url' => 'rampura.dhaka.gov.bd'),
            array('id' => '503','district_id' => '47','name' => 'Khilkhet','local_name' => 'খিলক্ষেত','url' => 'khilkhet.dhaka.gov.bd'),
            array('id' => '504','district_id' => '47','name' => 'Kafrul','local_name' => 'কাফরুল','url' => 'kafrul.dhaka.gov.bd'),
            array('id' => '505','district_id' => '47','name' => 'Sutrapur','local_name' => 'সুত্রাপুর','url' => 'sutrapur.dhaka.gov.bd'),
            array('id' => '506','district_id' => '47','name' => 'Jatrabari','local_name' => 'যাত্রাবাড়ী','url' => 'jatrabari.dhaka.gov.bd'),
            array('id' => '507','district_id' => '47','name' => 'Airport','local_name' => 'বিমানবন্দর','url' => 'airport.dhaka.gov.bd'),
            array('id' => '509','district_id' => '47','name' => 'Mugda','local_name' => 'মুগদা','url' => 'mugda.dhaka.gov.bd'),
            array('id' => '510','district_id' => '47','name' => 'Rupnagar','local_name' => 'রূপনগর','url' => 'rupnagar.dhaka.gov.bd'),
            array('id' => '511','district_id' => '47','name' => 'Vashantek','local_name' => 'বাসান্তেক','url' => 'vashantek.dhaka.gov.bd'),
            array('id' => '512','district_id' => '47','name' => 'Bhatara','local_name' => 'ভাতারা','url' => 'bhatara.dhaka.gov.bd'),
            array('id' => '513','district_id' => '47','name' => 'Banani','local_name' => 'বনানী','url' => 'banani.dhaka.gov.bd'),
            array('id' => '514','district_id' => '47','name' => 'Wari','local_name' => 'ওয়ারি','url' => 'wari.dhaka.gov.bd'),
            array('id' => '515','district_id' => '47','name' => 'Shahjahanpur' ,'local_name' => 'শাহজাহানপুর','url' => 'shahjahanpur.dhaka.gov.bd'),
            array('id' => '516','district_id' => '47','name' => 'Sher-e-Bangla Nagar','local_name' => 'শেরে বাংলা নগর','url' => 'sher-e-bangla-nagar.dhaka.gov.bd'),
            array('id' => '517','district_id' => '47','name' => 'Darus Salam','local_name' => 'দারুস সালাম','url' => 'darus-salam.dhaka.gov.bd'),
            array('id' => '519','district_id' => '47','name' => 'Dakshin','local_name' => 'দক্ষিণ','url' => 'dakshin.dhaka.gov.bd'),
            array('id' => '520','district_id' => '47','name' => 'Uttarkhan','local_name' => 'উত্তরখান','url' => 'uttarkhan.dhaka.gov.bd'),
            array('id' => '521','district_id' => '47','name' => 'Turag','local_name' => 'তুরাগ','url' => 'turag.dhaka.gov.bd'),
            array('id' => '522','district_id' => '47','name' => 'Uttara East','local_name' => 'উত্তরা পূর্ব','url' => 'uttara-east.dhaka.gov.bd'),
            array('id' => '523','district_id' => '47','name' => 'Uttara West','local_name' => 'উত্তরা পশ্চিম','url' => 'uttara-west.dhaka.gov.bd'),
            array('id' => '524','district_id' => '47','name' => 'Cantonment','local_name' => 'ক্যান্টনমেন্ট','url' => 'cantonment.dhaka.gov.bd'),
            array('id' => '526','district_id' => '47','name' => 'Pallabi','local_name' => 'পল্লবী','url' => 'pallabi.dhaka.gov.bd'),
            array('id' => '527','district_id' => '47','name' => 'Tejgaon Industrial Area','local_name' => 'তেজগাঁও শিল্প কর্মস্থল','url' => 'tejgaon-industrial-area.dhaka.gov.bd'),
            array('id' => '528','district_id' => '47','name' => 'Tejangao','local_name' => 'তেজগাঁও','url' => 'tejangao.dhaka.gov.bd'),
            array('id' => '529','district_id' => '47','name' => 'Sabujbagh','local_name' => 'সবুজবাগ','url' => 'sabujbagh.dhaka.gov.bd'),
            array('id' => '530','district_id' => '47','name' => 'Kadamtali','local_name' => 'কদমতলী','url' => 'kadamtali.dhaka.gov.bd'),
            array('id' => '531','district_id' => '47','name' => 'Chawkbazar','local_name' => 'চাউকবাজার','url' => 'chawkbazar.dhaka.gov.bd'),
            array('id' => '532','district_id' => '47','name' => 'Kamrangirchar','local_name' => 'কামরাঙ্গীরচর','url' => 'kamrangirchar.dhaka.gov.bd'),
            array('id' => '533','district_id' => '47','name' => 'Kotwali','local_name' => 'কোতোয়ালী','url' => 'kotwali.dhaka.gov.bd'),
            array('id' => '534','district_id' => '47','name' => 'Lalbagh','local_name' => 'লালবাগ','url' => 'lalbagh.dhaka.gov.bd'),
            array('id' => '535','district_id' => '47','name' => 'Paltan','local_name' => 'পল্টন','url' => 'paltan.dhaka.gov.bd'),
            array('id' => '536','district_id' => '47','name' => 'Kalabagan','local_name' => 'কলাবাগান','url' => 'kalabagan.dhaka.gov.bd'),
            array('id' => '537','district_id' => '47','name' => 'Shahbag','local_name' => 'শাহবাগ','url' => 'shahbag.dhaka.gov.bd'),
            array('id' => '538','district_id' => '47','name' => 'Bangshal','local_name' => 'বাংশল','url' => 'bangshal.dhaka.gov.bd'),
            array('id' => '539','district_id' => '47','name' => 'Motijheel','local_name' => 'মতিঝিল','url' => 'motijheel.dhaka.gov.bd'),
            array('id' => '540','district_id' => '47','name' => 'Hazaribagh','local_name' => 'হাজারীবাগ','url' => 'hazaribagh.dhaka.gov.bd'),
            array('id' => '541','district_id' => '47','name' => 'Ramna','local_name' => 'রামনা','url' => 'ramna.dhaka.gov.bd'),
            array('id' => '542','district_id' => '47','name' => 'Demra','local_name' => 'ডেমরা','url' => 'demra.dhaka.gov.bd'),
            array('id' => '543','district_id' => '47','name' => 'Newmarket','local_name' => 'নিউমার্কেট','url' => 'newmarket.dhaka.gov.bd'),
            array('id' => '544','district_id' => '47','name' => 'Shyampur','local_name' => 'শ্যামপুর','url' => 'shyampur.dhaka.gov.bd'),
            array('id' => '545','district_id' => '47','name' => 'Gandaria','local_name' => 'গন্দারিয়া','url' => 'gandaria.dhaka.gov.bd'),
            array('id' => '546','district_id' => '47','name' => 'Adabar','local_name' => 'আদাবার','url' => 'adabar.dhaka.gov.bd'),
            array('id' => '547','district_id' => '47','name' => 'Hatirjheel','local_name' => 'হাতিরঝিল','url' => 'hatirjheel.dhaka.gov.bd'),

        );

        foreach ($upazilas as $upazila) {
            Upazila::create($upazila);
        }
    }
}
