on:
  # pull_request:
  push:
    branches:
      - main


      # cd domains/frb-engineering.com/public_html/core/
      # composer2 update
      # php artisan db:seed --class=ThemeCustomizationSeeder
      # php artisan db:seed --class=ProductIDSeeder   
      # php artisan migrate
      # php artisan optimize
      # php artisan cache:clear



      # cd domains/api.shukkarun.com/public_html/
      # composer2 update
      # cp .env.example .env
      # sed -i 's/DB_DATABASE=.*/DB_DATABASE=u652464815_shukkarun/g' .env
      # sed -i 's/DB_USERNAME=.*/DB_USERNAME=u652464815_shukkarun/g' .env
      # sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=ueCV/7hoDp:3/g' .env
      # sed -i 's/API_ACCESS_TOKEN=.*/API_ACCESS_TOKEN=pS6rGh2wL8fPtQa4jX3zVkE7cM9bNuH5mWsY1dF6vC2bLnRqAzT7kPyZiJ8oQeS4/g' .env
      # sed -i 's/FRONTEND_URL=.*/FRONTEND_URL=https://shukkarun.com/g' .env
      # sed -i 's/APP_URL=.*/APP_URL=https://api.shukkarun.com/g' .env
      # mkdir -p public/uploads/admin/avatars
      # mkdir -p public/uploads/customer/avatars
      # mkdir -p public/uploads/images/banner
      # mkdir -p public/uploads/images/brands
      # mkdir -p public/uploads/images/category
      # mkdir -p public/uploads/images/general-setting
      # mkdir -p public/uploads/products/featured_banner
      # mkdir -p public/uploads/products/thumbnail
      # mkdir -p public/uploads/products/multiple_image
      # mkdir -p public/uploads/images/site_banner
      # mkdir -p public/uploads/images/sponsors
      # mkdir -p public/uploads/images/sub_categories
      # mkdir -p public/uploads/reviews
      # php artisan key:generate
      # php artisan jwt:secret
      # php artisan config:clear
      # php artisan migrate:fresh --seed
      # php artisan optimize
      # php artisan cache:clear


name: 🚀 Deploy website on push main
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
  

      - name: 🚚 Get latest code
        uses: actions/checkout@v2


      - name: 📂 Sync files in api.shukkarun.com
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: selopia.com
          username: u652464815.api.shukkarun.com
          password: dF@qa#4;k,vd
          exclude:  |
            **/.git*
            **/.git*/**
            **/public/upload*
            **/public/upload*/**
            **/public/json*
            **/public/json*/**
        continue-on-error: true     
    
      - name: executing remote ssh commands in api.shukkarun.com
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: selopia.com
          username: u652464815
          password: wew2Weqsdf@ssfa3
          port: 65002
          script: |
            cd domains/api.shukkarun.com/public_html/
            # composer2 update
            mkdir -p public/uploads/reviews
            php artisan migrate
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
    
      
        continue-on-error: true   






      - name: 📂 Sync files in api.vintbd.com
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: selopia.com
          username: u652464815.api.vintbd.com
          password: dF@qa#4;k,vd
          exclude:  |
            **/.git*
            **/.git*/**
            **/public/upload*
            **/public/upload*/**
            **/public/json*
            **/public/json*/**
        continue-on-error: true     
    
      - name: executing remote ssh commands in api.vintbd.com
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: selopia.com
          username: u652464815
          password: wew2Weqsdf@ssfa3
          port: 65002
          script: |
            cd domains/api.vintbd.com/public_html/
            # composer2 update
            mkdir -p public/uploads/reviews
            php artisan migrate
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
    
      
        continue-on-error: true  








      - name: 📂 Sync files in api.glamdesmit.com
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 194.163.35.14
          username: u652464815.api.glamdesmit.com
          password: dF@qa#4;k,vd
          exclude:  |
            **/.git*
            **/.git*/**
            **/public/upload*
            **/public/upload*/**
            **/public/json*
            **/public/json*/**
        continue-on-error: true     
    
      - name: executing remote ssh commands in api.glamdesmit.com
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: selopia.com
          username: u652464815
          password: wew2Weqsdf@ssfa3
          port: 65002
          script: |
            cd domains/api.glamdesmit.com/public_html/
            # composer2 update
            mkdir -p public/uploads/reviews
            php artisan migrate
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
    
      
        continue-on-error: true









      - name: 📂 Sync files in api.jannatistore.com
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: selopia.com
          username: u652464815.api.jannatistore.com
          password: dF@qa#4;k,vd
          exclude:  |
            **/.git*
            **/.git*/**
            **/public/upload*
            **/public/upload*/**
            **/public/json*
            **/public/json*/**
        continue-on-error: true     
    
      - name: executing remote ssh commands in api.jannatistore.com
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: selopia.com
          username: u652464815
          password: wew2Weqsdf@ssfa3
          port: 65002
          script: |
            cd domains/api.jannatistore.com/public_html/
            # composer2 update
            mkdir -p public/uploads/reviews
            php artisan migrate
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
    
      
        continue-on-error: true  








      - name: 📂 Sync files in apigreenbangla
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: selopia.com
          username: u652464815.apigreenbangla.selopia.com
          password: dF@qa#4;k,vd
          exclude:  |
            **/.git*
            **/.git*/**
            **/public/upload*
            **/public/upload*/**
            **/public/json*
            **/public/json*/**
        continue-on-error: true     
    
      - name: executing remote ssh commands in apigreenbangla
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: selopia.com
          username: u652464815
          password: wew2Weqsdf@ssfa3
          port: 65002
          script: |
            
            cd domains/apigreenbangla.selopia.com/public_html/
            # composer2 update
            mkdir -p public/uploads/reviews
            php artisan migrate
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
    
      
        continue-on-error: true  








      - name: 📂 Sync files in apibasictechnology.selopia.com
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: selopia.com
          username: u652464815.apibasictechnology.selopia.com
          password: dF@qa#4;k,vd
          exclude:  |
            **/.git*
            **/.git*/**
            **/public/upload*
            **/public/upload*/**
            **/public/json*
            **/public/json*/**
        continue-on-error: true     
    
      - name: executing remote ssh commands apibasictechnology.selopia.coma
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: selopia.com
          username: u652464815
          password: wew2Weqsdf@ssfa3
          port: 65002
          script: |
            
            cd domains/apibasictechnology.selopia.com/public_html/
            # composer2 update
            mkdir -p public/uploads/reviews
            php artisan migrate
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
    
      
        continue-on-error: true






      - name: 📂 Sync files in apitechview.selopia.com
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: selopia.com
          username: u652464815.apitechview.selopia.com
          password: dF@qa#4;k,vd
          exclude:  |
            **/.git*
            **/.git*/**
            **/public/upload*
            **/public/upload*/**
            **/public/json*
            **/public/json*/**
        continue-on-error: true     
    
      - name: executing remote ssh commands apitechview.selopia.com
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: selopia.com
          username: u652464815
          password: wew2Weqsdf@ssfa3
          port: 65002
          script: |
            
            cd domains/apitechview.selopia.com/public_html/
            # composer2 update
            mkdir -p public/uploads/reviews
            php artisan migrate
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
    
      
        continue-on-error: true






      - name: 📂 Sync files in api.yellowlix.com
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: selopia.com
          username: u652464815.api.yellowlix.com
          password: dF@qa#4;k,vd
          exclude:  |
            **/.git*
            **/.git*/**
            **/public/upload*
            **/public/upload*/**
            **/public/json*
            **/public/json*/**
        continue-on-error: true     
    
      - name: executing remote ssh commands api.yellowlix.com
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: selopia.com
          username: u652464815
          password: wew2Weqsdf@ssfa3
          port: 65002
          script: |
            
            cd domains/api.yellowlix.com/public_html/
            # composer2 update
            mkdir -p public/uploads/reviews
            php artisan migrate
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
    
      
        continue-on-error: true
        







      - name: 📂 Sync files in api.essencebd.store
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: selopia.com
          username: u652464815.api.essencebd.store
          password: dF@qa#4;k,vd
          exclude:  |
            **/.git*
            **/.git*/**
            **/public/upload*
            **/public/upload*/**
            **/public/json*
            **/public/json*/**
        continue-on-error: true     
    
      - name: executing remote ssh commands api.essencebd.store
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: selopia.com
          username: u652464815
          password: wew2Weqsdf@ssfa3
          port: 65002
          script: |
            
            cd domains/api.essencebd.store/public_html/
            # composer2 update
            mkdir -p public/uploads/reviews
            php artisan migrate
            php artisan config:clear
            php artisan cache:clear
            php artisan optimize
    
      
        continue-on-error: true  